# Generated by Django 4.2.23 on 2025-07-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers_images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
