# Generated by Django 4.2.23 on 2025-07-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_price_offer_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
