# Generated by Django 4.2.23 on 2025-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_storeprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
